version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/myapp
      - ./config/nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn lazystore.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db
    volumes:
      - .:/myapp
    expose:
      - "8000"
