# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=product.models.product_filename),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(upload_to=product.models.product_type_filename),
        ),
    ]
