# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bucket', '0002_auto_20171002_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit', 'Credit card'), ('cash', 'CASH')], default='cash', max_length=10)),
                ('sum', models.FloatField(default=0, verbose_name='total sum in receipt')),
                ('cash', models.FloatField(default=0, verbose_name='money amount, payed by buyer')),
                ('change', models.FloatField(default=0, verbose_name='change from cash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='bucket.Bucket')),
            ],
        ),
    ]
