# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='Device UID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Active')], default='inactive', max_length=10)),
                ('last_ping', models.DateTimeField(blank=True, null=True, verbose_name='last keep_alive signal')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='product.ProductType')),
            ],
        ),
    ]
