# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20171227_2248'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='product_type',
        ),
        migrations.AddField(
            model_name='device',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='product.Product'),
        ),
    ]
