# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'Bucket is not finished yet'), ('completed', 'Bucket completed with transaction')], default='in_progress', max_length=11)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='card.Card')),
            ],
        ),
        migrations.CreateModel(
            name='BucketItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='product name')),
                ('amount', models.FloatField(default=0, help_text='(weight, pieces, etc.)', verbose_name='Amount of product')),
                ('price', models.FloatField(default=0, verbose_name='Total product price')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bucket.Bucket')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bucket_items', to='product.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('credit', 'Credit card'), ('cash', 'CASH')], default='cash', max_length=10)),
                ('sum', models.FloatField(default=0, verbose_name='total sum in receipt')),
                ('cash', models.FloatField(default=0, verbose_name='money amount, payed by buyer')),
                ('change', models.FloatField(default=0, verbose_name='change from cash')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='bucket.Bucket')),
            ],
        ),
    ]
